services:
  prometheus-exporter:
    image: prom/node-exporter:latest
    ports: 
      - "9100:9100"
    container_name: mundosE-prometheus-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - mundosE-network

  sonarqube_db:
    image: postgres:13
    container_name: mundosE-sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - mundosE-sonarqube-db:/var/lib/postgresql
    networks:
      - mundosE-network
    
  sonarqube:
    image: sonarqube
    container_name: mundosE-sonarqube
    ports:
      - "9000:9000"
    depends_on:
      - sonarqube_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - mundosE-sonarqube:/opt/sonarqube
    networks:
      - mundosE-network

  mundosE-sonarqube:
    external: true
  mundosE-sonarqube-db:
    external: true

networks:
  mundosE-network:
    driver: bridge
