services:
  jenkins:
    build: jenkins
    container_name: mundosE-jenkins
    restart: always
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - mundosE-jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mundosE-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    container_name: mundosE-prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.config.file=/etc/prometheus/web.yml'
    networks:
      - mundosE-network
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: mundosE-grafana
    restart: always
    volumes:
      - mundosE-grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mundosE-network

  prometheus-exporter:
    image: prom/node-exporter:latest
    ports: 
      - "9100:9100"
    container_name: mundosE-prometheus-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - mundosE-network

volumes:
  mundosE-nexus-data:
  mundosE-jenkins-data:
    external: true
  mundosE-grafana:
    external: true

networks:
  mundosE-network:
    driver: bridge
