global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "mundose-monitor"

scrape_configs:
  - job_name: 'Servidor Web - Apache'
    static_configs:
      - targets: ['web.mundose.paivae.com:9100']

  - job_name: 'Servidor Monitoreo'
    static_configs:
      - targets: ['mundose.paivae.com:9100']

  - job_name: 'Sonarqube'
    static_configs:
      - targets: ['sonarqube.mundose.paivae.com:9100']