pipeline {
    environment {
        imagename = "paivae/mundose-web"
        dockerImage = ''
        containerName = 'mundose-webapp-test'
        dockerHubCredentials = 'DockerHubs'
    }
    agent any
    stages {
        stage('hello') {
            steps {
                sh 'echo Hello Jenkins!'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('Sonarqube') {
                    script {
                        scannerHome = tool 'Sonarqube';
                    }
                    sh "${scannerHome}/bin/sonar-scanner"
                }
            }
        }

        stage('Build Docker') {
            steps {
                dir(path: 'web/'){
                    sh 'docker build -t ${imagename} .'
                    echo 'Docker Build Finalizado'
                }
            }
        }

        stage('Test Docker image') {
            steps {
                dir(path: 'web/'){
                    sh 'docker run -d --name ${containerName} ${imagename}:latest'
                    echo 'Test Finalizado'
                }
            }
        }

        stage('Stop Docker image') {
            steps {
                dir(path: 'web/'){
                    sh "docker stop ${containerName} || true"
                    sh "docker rm ${containerName} || true"
                    echo 'Imagen borrada'
                }
            }
        }

         stage('Deploy Image') {
            steps {
                script {
                    // Use Jenkins credentials for Docker Hub login
                    withCredentials([usernamePassword(credentialsId: dockerHubCredentials, usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
 
                        // Push the image
                        sh "docker push ${imagename}:latest"
                    }
                }
            }
        }
    }
}

