pipeline {
    environment {
        imagename = "paivae/mundose-web"
        dockerImage = ''
        containerName = 'my-container'
        dockerHubCredentials = 'admin'
    }
    agent any
    stages {
        stage('hello') {
            steps {
                sh 'echo Hello Jenkins!'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('Sonarqube') {
                    script {
                        scannerHome = tool 'Sonarqube';
                    }
                    sh "${scannerHome}/bin/sonar-scanner"
                }
            }
        }

        stage('Build Docker') {
            steps {
                dir(path: 'web/'){
                    script {
                        dockerImage = docker.build "${imagename}:latest"
                    }
                    echo 'Docker Build Finalizado'
                }
            }
        }
    }
}

